<!doctype html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Вам подарили сертификат</title>
</head>
<body>
<h1>Hello, dear ${first_name} ${last_name}</h1>
<p>User with email ${email} just gave you a certificate from brand "${brand}"</p>
<p>Check it in your profile on our website "STUDENTS GIFTERY"</p>
<p>Bye</p>
<p></p>
</body>
</html>