GET http://localhost:8080/swagger-ui/index.html

###

GET http://localhost:8080/api/students-giftery/accounts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUxMDUzNTg2fQ.oUiCOW9UFtKl5q7rXu_E60tVl_YAzDq4YcqhTd3FB44

###

POST http://localhost:8080/api/students-giftery/signUp/
Content-Type: application/json

{
  "firstName": "Daniil",
  "lastName": "Korotaev",
  "email": "daniil.korotaev@gmail.com",
  "password": "12345"
}

### test account

POST http://localhost:8080/api/students-giftery/signUp/
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test.test@gmail.com",
  "password": "test"
}

###

POST http://localhost:8080/api/students-giftery/signIn/
Content-Type: application/json

{
  "email": "daniil.korotaev@gmail.com",
  "password": "12345"
}

### test account

POST http://localhost:8080/api/students-giftery/signIn/
Content-Type: application/json

{
  "email": "test.test@gmail.com",
  "password": "test"
}

### create organization

POST http://localhost:8080/api/students-giftery/organizations/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUxMDYyNTM2fQ.LZHMklys3S0KPBoov-JH2MUsJpT5k6jU17N-rfeESrE

{
  "name": "Skuratov Сoffee",
  "description": "Coffee houses in 7 cities of Russia."
}

### get all organization

GET http://localhost:8080/api/students-giftery/organizations/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTM5MjI0fQ.BcRMgfgUWBGUR4-BKWR-s90-NYG-grnBUzuYiLIkdyY

### get all account by organization id

GET http://localhost:8080/api/students-giftery/accounts/getByOrganization?organizationId=2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiZXhwIjoxNjUwMTgzMDcyfQ.XhWGiROnwZK06QR_W4FJDphoK8X8SNDpBsPV8uSVCDE

### join to organization

POST http://localhost:8080/api/students-giftery/organizations/join?organizationId=2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiZXhwIjoxNjUwMTg0NzQyfQ.HaBfcrIQdLIP0YC86ES3gkj3yi0W1VTFk1t0IIuyXN8

### deny join request

POST http://localhost:8080/api/students-giftery/organizations/denyJoin?requestId=7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTg0NjA2fQ.Qc7TXUce6UE39X3kvVVWPOpwYkWMJF99DyE3QD_84Q8

### confirm join request

POST http://localhost:8080/api/students-giftery/organizations/confirmJoin?requestId=8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTg0Nzk5fQ.kn0Umn9F25BEP45IEKpJIXBlqU1hy-WMY9Kdzs3IAME

###

POST http://localhost:8080/api/students-giftery/organizations/unjoin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiZXhwIjoxNjUwMjA0ODU0fQ.zNYQcAkx4NQyslPM_HnG4id0zRQ0EU8Kmu8nAPRxdoU

###

POST http://localhost:8080/api/students-giftery/brands/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiZXhwIjoxNjUyNDI5MzIzfQ.gOGwT_psvZVFuOodqJ1_UKi9YQghK5JQ3ufw6IpXpWM
Content-Type: application/json

{
  "brandName": "somename",
  "description": "somedescription"
}

###

POST http://localhost:8080/api/students-giftery/certificates/1/buy/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiZXhwIjoxNjUxNzQxNTI2fQ.ziRfyGdc_c0jrawNhRrvnFlS7bg6f3MQ2vjkr0q09H4

###

GET http://localhost:8080/get/4